### DISCUSSION TITLE
Custom K3S Config with MetalLB and Traefik

### DISCUSSION THREAD

**Discussion by mraerino** [ffddorf/k3os-on-proxmox#4] [Show and tell]
I experimented with k3s on our VM cluster.

- Uses MetalLB as LoadBalancer
- Replaces the default k3s traefik with the official helmchart and custom options
- Installs cert-manager for automatic TLS certs (via Letsencrypt/ACME)

It's terraform-based, you can see it here: https://github.com/mraerino/k3s-opinions

**Comment by mraerino** [comment]
cc @nomaster

**Comment by mraerino** [comment]
some of the k3s provisioning is still a bit manual.

- we should be able to bootstrap the node using k3os as a base image
- user creation should be moved into terraform

**Comment by mraerino** [comment]
example ingress manifest using this setup:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: prometheus-ingress
  namespace: network-monitoring
spec:
  rules:
  - host: prometheus.netmetrics.freifunk-duesseldorf.de
    http:
      paths:
      - backend:
          service:
            name: prometheus
            port:
              number: 9090
  tls:
  - hosts:
    - prometheus.netmetrics.freifunk-duesseldorf.de
    secretName: prometheus-ingress-tls
```
